// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngowayhnjjrzrjfwhdbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nb3dheWhuampyenJqZndoZGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODEwMjQsImV4cCI6MjA2NzQ1NzAyNH0.q_dEcf6U7-CklI4INsRICcGX23y50N6mgt4CvJj1CJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});